adding env variable

diff --git a/template.yml b/template.yml
--- a/template.yml
+++ b/template.yml
@@ -122,113 +122,113 @@ Resources:
       Runtime: python3.9
 
 ################## SSM BOOTSRAP HANDLER ###############
-  ODDC9OutputBucket:
-    Type: AWS::S3::Bucket
-    DeletionPolicy: Delete
+  # ODDC9OutputBucket:
+  #   Type: AWS::S3::Bucket
+  #   DeletionPolicy: Delete
 
-  ODDC9SSMDocument: 
-    Type: AWS::SSM::Document
-    Properties: 
-      Content: Yaml
-      DocumentType: Command
-      Content: 
-        schemaVersion: '2.2'
-        description: Bootstrap Cloud9 Instance
-        mainSteps:
-        - action: aws:runShellScript
-          name: ODDC9bootstrap
-          inputs:
-            runCommand:
-            - "#!/bin/bash"
-            - date
-            - echo LANG=en_US.utf-8 >> /etc/environment
-            - echo LC_ALL=en_US.UTF-8 >> /etc/environment
-            - . /home/ec2-user/.bashrc
-            - yum -y remove aws-cli; yum -y install sqlite telnet jq strace tree gcc glibc-static python3 python3-pip gettext bash-completion
-            - echo '=== CONFIGURE default python version ==='
-            - PATH=$PATH:/usr/bin
-            - alternatives --set python /usr/bin/python3.7
-            - echo '=== INSTALL and CONFIGURE default software components ==='
-            - sudo -H -u ec2-user bash -c "pip install --user -U boto boto3 botocore awscli aws-sam-cli"
-            - echo '=== Resizing the Instance volume'
-            - !Sub SIZE=15
-            - !Sub REGION=${AWS::Region}
-            - |
-              INSTANCEID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
-              VOLUMEID=$(aws ec2 describe-instances \
-                --instance-id $INSTANCEID \
-                --query "Reservations[0].Instances[0].BlockDeviceMappings[0].Ebs.VolumeId" \
-                --output text --region $REGION)
-              aws ec2 modify-volume --volume-id $VOLUMEID --size $SIZE --region $REGION
-              while [ \
-                "$(aws ec2 describe-volumes-modifications \
-                  --volume-id $VOLUMEID \
-                  --filters Name=modification-state,Values="optimizing","completed" \
-                  --query "length(VolumesModifications)"\
-                  --output text --region $REGION)" != "1" ]; do
-              sleep 1
-              done
-              if [ $(readlink -f /dev/xvda) = "/dev/xvda" ]
-              then
-                sudo growpart /dev/xvda 1
-                STR=$(cat /etc/os-release)
-                SUB="VERSION_ID=\"2\""
-                if [[ "$STR" == *"$SUB"* ]]
-                then
-                  sudo xfs_growfs -d /
-                else
-                  sudo resize2fs /dev/xvda1
-                fi
-              else
-                sudo growpart /dev/nvme0n1 1
-                STR=$(cat /etc/os-release)
-                SUB="VERSION_ID=\"2\""
-                if [[ "$STR" == *"$SUB"* ]]
-                then
-                  sudo xfs_growfs -d /
-                else
-                  sudo resize2fs /dev/nvme0n1p1
-                fi
-              fi
-            - echo '=== INSTALL and CONFIGURE amplify and setting ENVIRONMENT VARS ==='
-            - sudo -H -u ec2-user bash -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash" && sudo -H -u ec2-user bash -c ". ~/.nvm/nvm.sh && nvm install node" && sudo -H -u ec2-user bash -c ". ~/.nvm/nvm.sh && npm install -g @aws-amplify/cli"
-            - echo '=== INSTALL and CONFIGURE IaC Tools ==='
-            - sudo -H -u ec2-user bash -c ". ~/.nvm/nvm.sh && npm install -g aws-cdk"
-            - sudo -H -u ec2-user bash -c ". ~/.nvm/nvm.sh && npm install -g artillery"
-            - echo '=== CONFIGURE kubecrtl and setting ENVIRONMENT VARS ==='
-            - sudo -H -u ec2-user bash -c ". /etc/profile.d/bash_completion.sh"
-            - sudo -H -u ec2-user bash -c ". ~/.bash_completion"
-            - echo '=== CONFIGURE eksctl and setting ENVIRONMENT VARS ==='
-            - sudo -H -u ec2-user bash -c ". /etc/profile.d/bash_completion.sh"
-            - sudo -H -u ec2-user bash -c ". ~/.bash_completion"
-            - echo '=== CONFIGURE awscli and setting ENVIRONMENT VARS ==='
-            - echo "complete -C '/usr/local/bin/aws_completer' aws" >> /home/ec2-user/.bashrc
-            - mkdir /home/ec2-user/.aws
-            - echo '[default]' > /home/ec2-user/.aws/config
-            - echo 'output = json' >> /home/ec2-user/.aws/config
-            - chmod 600 /home/ec2-user/.aws/config && chmod 600 /home/ec2-user/.aws/credentials
-            - echo 'PATH=$PATH:/usr/local/bin' >> /home/ec2-user/.bashrc
-            - echo 'export PATH' >> /home/ec2-user/.bashrc
-            - echo '=== CLEANING /home/ec2-user ==='
-            - for f in cloud9; do rm -rf /home/ec2-user/$f; done
-            - chown -R ec2-user:ec2-user /home/ec2-user/
-            - echo '=== PREPARE REBOOT in 1 minute with at ==='
-            - FILE=$(mktemp) && echo $FILE && echo '#!/bin/bash' > $FILE && echo 'reboot -f --verbose' >> $FILE && at now + 1 minute -f $FILE
-            - echo "Bootstrap completed with return code $?"
+  # ODDC9SSMDocument: 
+  #   Type: AWS::SSM::Document
+  #   Properties: 
+  #     Content: Yaml
+  #     DocumentType: Command
+  #     Content: 
+  #       schemaVersion: '2.2'
+  #       description: Bootstrap Cloud9 Instance
+  #       mainSteps:
+  #       - action: aws:runShellScript
+  #         name: ODDC9bootstrap
+  #         inputs:
+  #           runCommand:
+  #           - "#!/bin/bash"
+  #           - date
+  #           - echo LANG=en_US.utf-8 >> /etc/environment
+  #           - echo LC_ALL=en_US.UTF-8 >> /etc/environment
+  #           - . /home/ec2-user/.bashrc
+  #           - yum -y remove aws-cli; yum -y install sqlite telnet jq strace tree gcc glibc-static python3 python3-pip gettext bash-completion
+  #           - echo '=== CONFIGURE default python version ==='
+  #           - PATH=$PATH:/usr/bin
+  #           - alternatives --set python /usr/bin/python3.7
+  #           - echo '=== INSTALL and CONFIGURE default software components ==='
+  #           - sudo -H -u ec2-user bash -c "pip install --user -U boto boto3 botocore awscli aws-sam-cli"
+  #           - echo '=== Resizing the Instance volume'
+  #           - !Sub SIZE=15
+  #           - !Sub REGION=${AWS::Region}
+  #           - |
+  #             INSTANCEID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
+  #             VOLUMEID=$(aws ec2 describe-instances \
+  #               --instance-id $INSTANCEID \
+  #               --query "Reservations[0].Instances[0].BlockDeviceMappings[0].Ebs.VolumeId" \
+  #               --output text --region $REGION)
+  #             aws ec2 modify-volume --volume-id $VOLUMEID --size $SIZE --region $REGION
+  #             while [ \
+  #               "$(aws ec2 describe-volumes-modifications \
+  #                 --volume-id $VOLUMEID \
+  #                 --filters Name=modification-state,Values="optimizing","completed" \
+  #                 --query "length(VolumesModifications)"\
+  #                 --output text --region $REGION)" != "1" ]; do
+  #             sleep 1
+  #             done
+  #             if [ $(readlink -f /dev/xvda) = "/dev/xvda" ]
+  #             then
+  #               sudo growpart /dev/xvda 1
+  #               STR=$(cat /etc/os-release)
+  #               SUB="VERSION_ID=\"2\""
+  #               if [[ "$STR" == *"$SUB"* ]]
+  #               then
+  #                 sudo xfs_growfs -d /
+  #               else
+  #                 sudo resize2fs /dev/xvda1
+  #               fi
+  #             else
+  #               sudo growpart /dev/nvme0n1 1
+  #               STR=$(cat /etc/os-release)
+  #               SUB="VERSION_ID=\"2\""
+  #               if [[ "$STR" == *"$SUB"* ]]
+  #               then
+  #                 sudo xfs_growfs -d /
+  #               else
+  #                 sudo resize2fs /dev/nvme0n1p1
+  #               fi
+  #             fi
+  #           - echo '=== INSTALL and CONFIGURE amplify and setting ENVIRONMENT VARS ==='
+  #           - sudo -H -u ec2-user bash -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash" && sudo -H -u ec2-user bash -c ". ~/.nvm/nvm.sh && nvm install node" && sudo -H -u ec2-user bash -c ". ~/.nvm/nvm.sh && npm install -g @aws-amplify/cli"
+  #           - echo '=== INSTALL and CONFIGURE IaC Tools ==='
+  #           - sudo -H -u ec2-user bash -c ". ~/.nvm/nvm.sh && npm install -g aws-cdk"
+  #           - sudo -H -u ec2-user bash -c ". ~/.nvm/nvm.sh && npm install -g artillery"
+  #           - echo '=== CONFIGURE kubecrtl and setting ENVIRONMENT VARS ==='
+  #           - sudo -H -u ec2-user bash -c ". /etc/profile.d/bash_completion.sh"
+  #           - sudo -H -u ec2-user bash -c ". ~/.bash_completion"
+  #           - echo '=== CONFIGURE eksctl and setting ENVIRONMENT VARS ==='
+  #           - sudo -H -u ec2-user bash -c ". /etc/profile.d/bash_completion.sh"
+  #           - sudo -H -u ec2-user bash -c ". ~/.bash_completion"
+  #           - echo '=== CONFIGURE awscli and setting ENVIRONMENT VARS ==='
+  #           - echo "complete -C '/usr/local/bin/aws_completer' aws" >> /home/ec2-user/.bashrc
+  #           - mkdir /home/ec2-user/.aws
+  #           - echo '[default]' > /home/ec2-user/.aws/config
+  #           - echo 'output = json' >> /home/ec2-user/.aws/config
+  #           - chmod 600 /home/ec2-user/.aws/config && chmod 600 /home/ec2-user/.aws/credentials
+  #           - echo 'PATH=$PATH:/usr/local/bin' >> /home/ec2-user/.bashrc
+  #           - echo 'export PATH' >> /home/ec2-user/.bashrc
+  #           - echo '=== CLEANING /home/ec2-user ==='
+  #           - for f in cloud9; do rm -rf /home/ec2-user/$f; done
+  #           - chown -R ec2-user:ec2-user /home/ec2-user/
+  #           - echo '=== PREPARE REBOOT in 1 minute with at ==='
+  #           - FILE=$(mktemp) && echo $FILE && echo '#!/bin/bash' > $FILE && echo 'reboot -f --verbose' >> $FILE && at now + 1 minute -f $FILE
+  #           - echo "Bootstrap completed with return code $?"
   
-  ODDC9BootstrapAssociation: 
-    Type: AWS::SSM::Association
-    DependsOn: ODDC9OutputBucket 
-    Properties: 
-      Name: !Ref ODDC9SSMDocument
-      OutputLocation: 
-        S3Location:
-          OutputS3BucketName: !Ref ODDC9OutputBucket
-          OutputS3KeyPrefix: bootstrapoutput
-      Targets:
-        - Key: tag:SSMBootstrap
-          Values:
-          - Active
+  # ODDC9BootstrapAssociation: 
+  #   Type: AWS::SSM::Association
+  #   DependsOn: ODDC9OutputBucket 
+  #   Properties: 
+  #     Name: !Ref ODDC9SSMDocument
+  #     OutputLocation: 
+  #       S3Location:
+  #         OutputS3BucketName: !Ref ODDC9OutputBucket
+  #         OutputS3KeyPrefix: bootstrapoutput
+  #     Targets:
+  #       - Key: tag:SSMBootstrap
+  #         Values:
+  #         - Active
 
 ################## Cloud9 #####################
   ODDC9InstanceProfile:
@@ -240,7 +240,7 @@ Resources:
 
   ODDC9Instance:
     Description: "-"
-    DependsOn: ODDC9BootstrapAssociation
+    # DependsOn: ODDC9BootstrapAssociation
     Type: AWS::Cloud9::EnvironmentEC2
     Properties:
       Description: "AWS Cloud9 instance for Observability Driven Development"
